version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ${ENV_FILE:-./backend/.env}
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "80"
    env_file:
      - ${ENV_FILE:-./frontend/.env}
    depends_on:
      - backend
    restart: unless-stopped 