services:
  order_flow:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:your-super-secret-and-long-postgres-password@db:5432/postgres?sslmode=disable
      - PORT=3000
    networks:
      - supabase_default
    restart: unless-stopped

networks:
  supabase_default:
    external: true
    name: supabase_default